collections:
  genres:
    output: true

  films:
    output: true

  decades:
    output: true

  countries:
    output: true

  directors:
    output: true


permalink: pretty


defaults:
    scope:
      type: pages
    values:
      permalink: /:path/:basename:output_ext
